/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LlmInfoRouteImport } from './routes/llm-info'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VistosSlugRouteImport } from './routes/vistos.$slug'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AvaliacaoObrigadoRouteImport } from './routes/avaliacao.obrigado'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTrackingRouteImport } from './routes/admin.tracking'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSegmentosRouteImport } from './routes/admin.segmentos'
import { Route as AdminMidiaRouteImport } from './routes/admin.midia'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminConteudoRouteImport } from './routes/admin.conteudo'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAbRouteImport } from './routes/admin.ab'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmInfoRoute = LlmInfoRouteImport.update({
  id: '/llm-info',
  path: '/llm-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VistosSlugRoute = VistosSlugRouteImport.update({
  id: '/vistos/$slug',
  path: '/vistos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AvaliacaoObrigadoRoute = AvaliacaoObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => AvaliacaoRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrackingRoute = AdminTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegmentosRoute = AdminSegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMidiaRoute = AdminMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbRoute = AdminAbRouteImport.update({
  id: '/ab',
  path: '/ab',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avaliacao': typeof AvaliacaoRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/llm-info': typeof LlmInfoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/ab': typeof AdminAbRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/segmentos': typeof AdminSegmentosRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/avaliacao/obrigado': typeof AvaliacaoObrigadoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lp/$slug': typeof LpSlugRoute
  '/vistos/$slug': typeof VistosSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/llm-info': typeof LlmInfoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/ab': typeof AdminAbRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/segmentos': typeof AdminSegmentosRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/avaliacao/obrigado': typeof AvaliacaoObrigadoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lp/$slug': typeof LpSlugRoute
  '/vistos/$slug': typeof VistosSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/avaliacao': typeof AvaliacaoRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/llm-info': typeof LlmInfoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/ab': typeof AdminAbRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/segmentos': typeof AdminSegmentosRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/avaliacao/obrigado': typeof AvaliacaoObrigadoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lp/$slug': typeof LpSlugRoute
  '/vistos/$slug': typeof VistosSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avaliacao'
    | '/blog'
    | '/contato'
    | '/llm-info'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/ab'
    | '/admin/blog'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/leads'
    | '/admin/links'
    | '/admin/login'
    | '/admin/midia'
    | '/admin/segmentos'
    | '/admin/seo'
    | '/admin/tracking'
    | '/admin/usuarios'
    | '/avaliacao/obrigado'
    | '/blog/$slug'
    | '/lp/$slug'
    | '/vistos/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avaliacao'
    | '/blog'
    | '/contato'
    | '/llm-info'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/ab'
    | '/admin/blog'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/leads'
    | '/admin/links'
    | '/admin/login'
    | '/admin/midia'
    | '/admin/segmentos'
    | '/admin/seo'
    | '/admin/tracking'
    | '/admin/usuarios'
    | '/avaliacao/obrigado'
    | '/blog/$slug'
    | '/lp/$slug'
    | '/vistos/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avaliacao'
    | '/blog'
    | '/contato'
    | '/llm-info'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/ab'
    | '/admin/blog'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/leads'
    | '/admin/links'
    | '/admin/login'
    | '/admin/midia'
    | '/admin/segmentos'
    | '/admin/seo'
    | '/admin/tracking'
    | '/admin/usuarios'
    | '/avaliacao/obrigado'
    | '/blog/$slug'
    | '/lp/$slug'
    | '/vistos/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvaliacaoRoute: typeof AvaliacaoRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  LlmInfoRoute: typeof LlmInfoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  LpSlugRoute: typeof LpSlugRoute
  VistosSlugRoute: typeof VistosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-info': {
      id: '/llm-info'
      path: '/llm-info'
      fullPath: '/llm-info'
      preLoaderRoute: typeof LlmInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vistos/$slug': {
      id: '/vistos/$slug'
      path: '/vistos/$slug'
      fullPath: '/vistos/$slug'
      preLoaderRoute: typeof VistosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/avaliacao/obrigado': {
      id: '/avaliacao/obrigado'
      path: '/obrigado'
      fullPath: '/avaliacao/obrigado'
      preLoaderRoute: typeof AvaliacaoObrigadoRouteImport
      parentRoute: typeof AvaliacaoRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tracking': {
      id: '/admin/tracking'
      path: '/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AdminTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/segmentos': {
      id: '/admin/segmentos'
      path: '/segmentos'
      fullPath: '/admin/segmentos'
      preLoaderRoute: typeof AdminSegmentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/midia': {
      id: '/admin/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AdminMidiaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ab': {
      id: '/admin/ab'
      path: '/ab'
      fullPath: '/admin/ab'
      preLoaderRoute: typeof AdminAbRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAbRoute: typeof AdminAbRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMidiaRoute: typeof AdminMidiaRoute
  AdminSegmentosRoute: typeof AdminSegmentosRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminTrackingRoute: typeof AdminTrackingRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbRoute: AdminAbRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMidiaRoute: AdminMidiaRoute,
  AdminSegmentosRoute: AdminSegmentosRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminTrackingRoute: AdminTrackingRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AvaliacaoRouteChildren {
  AvaliacaoObrigadoRoute: typeof AvaliacaoObrigadoRoute
}

const AvaliacaoRouteChildren: AvaliacaoRouteChildren = {
  AvaliacaoObrigadoRoute: AvaliacaoObrigadoRoute,
}

const AvaliacaoRouteWithChildren = AvaliacaoRoute._addFileChildren(
  AvaliacaoRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvaliacaoRoute: AvaliacaoRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  LlmInfoRoute: LlmInfoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  LpSlugRoute: LpSlugRoute,
  VistosSlugRoute: VistosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
